export const BASE_URL = "http://192.81.132.51:5000"
export const PRODUCT_URL = "/api/products"
export const USERS_URL = "/api/users"
export const ORDERS_URL = "/api/order"
export const PAYPAL_URL = "/api/config/paypal"